def menu_principal():
    print("\n--- Sistema de Reembolsos ---")
    print("1 Iniciar sesión")
    print("2 Registrarse como cliente")
    print("0 Salir")

def menu_administrador():
    print("\n--- Menu Administrador ---")
    print("1 Ver usuarios")
    print("2 Ver solicitudes de reembolso")
    print("3 Aceptar solicitud")
    print("4 Rechazar solicitud")
    print("5 Eliminar solicitud")
    print("6 Contar solicitudes de Reembolsos por Producto")
    print("7 Ver estadisticas por medio de pago")
    print("8 Ver clientes frecuentes")
    print("9 Ver solicitudes de reembolso con filtro personalizado")
    print("10 Eliminar usuario")
    print("11 Ver lista de productos")
    print("12 Agregar nuevo producto")
    print("13 Actualizar producto")
    print("0 Salir")

def menu_cliente():
    print("\n--- Menu Cliente ---")
    print("1 Crear solicitud de reembolso")
    print("2 Ver tus solicitudes")
    print("3 Ver tus solicitudes aprobadas")
    print("4 Eliminar solicitud")
    print("0 Salir")
